version: '3.8'

services:
  nextjs_app_1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./public:/app/public
    environment:
      - AUTH_SECRET = secret
      - DATABASE_URL = postgres://postgres:123456@127.0.0.1:5432/ghostprotocols

  nextjs_app_2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - ./public:/app/public
    environment:
      - AUTH_SECRET=secret
      - DATABASE_URL=postgres://postgres:123456@127.0.0.1:5432/ghostprotocols
